import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getAISignal, getSymbols, type AISignal } from "@/services/mt5Api";
import { Zap, Play, Loader2, TrendingUp, TrendingDown, Brain, RefreshCw } from "lucide-react";
import { toast } from "sonner";

export default function Signals() {
  const [signals, setSignals] = useState<AISignal[]>([]);
  const [scanning, setScanning] = useState(false);
  const [autoRefresh, setAutoRefresh] = useState(true);

  const scan = async () => {
    setScanning(true);
    const newSignals: AISignal[] = [];

    let symbols: string[] = [];
    try {
      symbols = await getSymbols();
    } catch (e) {
      console.error("Failed to fetch symbols", e);
      symbols = ["EURUSD", "XAUUSD"]; // Fallback
    }

    for (const symbol of symbols) {
      try {
        const signal = await getAISignal(symbol);
        newSignals.push(signal);
      } catch (err) {
        console.error(`Failed to get signal for ${symbol}:`, err);
      }
    }

    setSignals(newSignals.sort((a, b) => b.confidence - a.confidence));
    setScanning(false);

    const tradeable = newSignals.filter(s => s.signal !== "HOLD" && s.confidence > 0.6);
    if (tradeable.length > 0) {
      toast.success(`Found ${tradeable.length} high-confidence signal(s)`);
    }
  };

  useEffect(() => {
    scan();
    if (autoRefresh) {
      const interval = setInterval(scan, 60000); // Refresh every minute
      return () => clearInterval(interval);
    }
  }, [autoRefresh]);

  const confidenceColor = (confidence: number) => {
    if (confidence >= 0.8) return "text-profit";
    if (confidence >= 0.6) return "text-warning";
    return "text-muted-foreground";
  };

  const confidenceLabel = (confidence: number) => {
    if (confidence >= 0.8) return "🎯 VERY HIGH";
    if (confidence >= 0.6) return "🔥 HIGH";
    if (confidence >= 0.4) return "⚡ MEDIUM";
    return "📊 LOW";
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Brain className="h-6 w-6 text-primary" />
            AI Signals
          </h1>
          <p className="text-sm text-muted-foreground">
            Neural network predictions for multiple symbols
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant={autoRefresh ? "default" : "outline"}
            size="sm"
            onClick={() => setAutoRefresh(!autoRefresh)}
          >
            <RefreshCw className={`h-4 w-4 mr-2 ${autoRefresh ? "animate-spin" : ""}`} />
            Auto
          </Button>
          <Button onClick={scan} disabled={scanning} className="gap-2">
            {scanning ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Play className="h-4 w-4" />
            )}
            Scan Now
          </Button>
        </div>
      </div>

      {/* Info Card */}
      <Card className="border-primary/20 bg-primary/5">
        <CardContent className="flex items-center gap-3 py-4">
          <Brain className="h-5 w-5 text-primary" />
          <div className="flex-1">
            <p className="text-sm font-medium">AI-Powered Analysis</p>
            <p className="text-xs text-muted-foreground">
              Signals generated by trained neural network using 20+ technical indicators
            </p>
          </div>
          <Badge variant="outline" className="text-xs">
            Confidence Threshold: 60%
          </Badge>
        </CardContent>
      </Card>

      {/* Signals */}
      {signals.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-16">
            <Zap className="mb-4 h-12 w-12 text-muted-foreground/30" />
            <p className="text-sm text-muted-foreground">
              Loading AI signals...
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4 md:grid-cols-2">
          {signals.map((signal) => (
            <Card key={signal.symbol} className="overflow-hidden">
              <div
                className={`h-1 ${signal.signal === "BUY" ? "bg-profit" :
                    signal.signal === "SELL" ? "bg-loss" : "bg-muted"
                  }`}
              />
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className="text-lg font-bold font-mono">
                      {signal.symbol}
                    </span>
                    <Badge
                      variant={signal.signal === "HOLD" ? "secondary" : "outline"}
                      className={
                        signal.signal === "BUY"
                          ? "border-profit/30 text-profit"
                          : signal.signal === "SELL"
                            ? "border-loss/30 text-loss"
                            : ""
                      }
                    >
                      {signal.signal === "BUY" && <TrendingUp className="mr-1 h-3 w-3" />}
                      {signal.signal === "SELL" && <TrendingDown className="mr-1 h-3 w-3" />}
                      {signal.signal}
                    </Badge>
                  </div>
                  <span className={`text-sm font-bold ${confidenceColor(signal.confidence)}`}>
                    {confidenceLabel(signal.confidence)}
                  </span>
                </div>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="rounded-lg bg-secondary p-3">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs text-muted-foreground">AI Confidence</span>
                    <span className={`text-sm font-bold font-mono ${confidenceColor(signal.confidence)}`}>
                      {(signal.confidence * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="h-2 bg-background rounded-full overflow-hidden">
                    <div
                      className={`h-full transition-all ${signal.confidence >= 0.6 ? "bg-profit" : "bg-muted-foreground"
                        }`}
                      style={{ width: `${signal.confidence * 100}%` }}
                    />
                  </div>
                </div>

                {signal.signal !== "HOLD" && signal.sl && signal.tp && (
                  <div className="grid grid-cols-4 gap-2 rounded-lg bg-secondary p-3 text-xs font-mono">
                    <div>
                      <p className="text-muted-foreground">Entry</p>
                      <p className="font-medium">{signal.current_price.toFixed(5)}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">SL</p>
                      <p className="text-loss">{signal.sl.toFixed(5)}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">TP</p>
                      <p className="text-profit">{signal.tp.toFixed(5)}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground">ATR</p>
                      <p className="font-medium">{signal.atr.toFixed(5)}</p>
                    </div>
                  </div>
                )}

                <p className="text-[10px] text-muted-foreground font-mono">
                  {new Date(signal.timestamp).toLocaleString()}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
